### ISSUE TITLE
Some Station IDs Are Longer Than Four Characters

### ISSUE THREAD

**Issue by chbarts** [sramsay/nowa#1]
As an example, the Rocky Boy station in Montana has the station ID `RCBM8` which your code will not accept.

**Comment by sramsay** [comment]
Fixed with [128ca7e](https://github.com/sramsay/nowa/commit/128ca7eb1da4b18e3351a97220cf01a3747bf4bf), though it appears that 5-character station IDs do not (ever?) contain METAR data or text description fields.  I need to figure out if this is a property of these particular stations, or if it is possible that not all stations have these fields in general (I suppose it wouldn't matter, but if there's a distinction here, I'd like to understand it).

**Comment by sramsay** [comment]
Spoke too soon.  The JSON data sometimes has data in these fields and sometimes doesn't (in typical NWS fashion).  Will investigate.

**Comment by sramsay** [comment]
"Works," in the sense that it doesn't error out.  But still not sure about 5-character IDs.
